### ISSUE TITLE
Contains Models laravel return false

### ISSUE THREAD

**Issue by FuriosoJack** [ramsey/collection#60]
## Describe the bug

Does not return correct value when using contasins with a collection of laravel models

## To Reproduce...

Steps to reproduce the behavior (include code examples, if applicable):

1. Create script `foo.php` and add the following:

    ``` php
    <?php
    require_once 'vendor/autoload.php';

    $collection = new Ramsey\Collection\Collection(\App\User::class);

   $model = \App\User::find(1);
    $collection->add($model);
   $model2 =  \App\User::find(1);
   $collection->contains($model2); //Return false
    ```

2. Execute the script from a terminal:

    ``` bash
    $ php foo.php
    ```

3. See output similar to the following:

    ```
   The ouput the output must be true ...
    ```

## Environment details

 - OS: Linux Ubuntu 18.04.1
 - PHP version: 7.4
 - ramsey/collection version 1.1.0

**Comment by SimoTod** [comment]
HI @FuriosoJack It's the expected behaviour, please see https://github.com/ramsey/collection/blob/master/src/AbstractCollection.php#L73 .
Contains performs a strict equality check by default which means that it only returns true if the collection contains the same instance of an object. 

It's the same difference between `===` and `==`
```php
$a = new stdClass();
$b = new stdClass();

var_dump($a === $b); //bool(false)
var_dump($a == $b);   //bool(false)
```
**Contains also accept a second parameter and setting it to false will switch to loose comparison which is what you are after in this case.**

```php
require_once 'vendor/autoload.php';

$collection = new Ramsey\Collection\Collection(\App\User::class);

$model = \App\User::find(1);
$collection->add($model);
$model2 =  \App\User::find(1);
$collection->contains($model2); //Return false
$collection->contains($model2, false); //Return true
```

I hope it helps.

**Comment by ramsey** [comment]
Does this help, @FuriosoJack ?
