### ISSUE TITLE
How to restrict collection data values

### ISSUE THREAD

**Issue by jmwebservices** [ramsey/collection#67]
## How do I impose restrictions on data values added to a collection?

I need a collection that not only limits the *type* of data added, but also imposes restrictions on the data *values*. I browsed through the Wiki, ReadMe and tests but could not find any indication that this is possible. Any ideas?

**Comment by ramsey** [comment]
The library is currently optimized for *typed* collections, which doesn't involve validation. What you're asking for is validation. Adding validators to collections might be nice, but there are a lot of issues to consider, such as what happens to an item already in the collection when its value changes so that it is no longer valid for the collection.

**Comment by jmwebservices** [comment]
Got it. Thanks for the reply and for such a great project.
